### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by AugustH** [MatthiasReumann/webuntis-to-ics-calendar#1]
isn't this a duplicate of a webuntis-buildin: 
in your webuntis-profile there is a point `Freigaben`(Shares?) which gives a link to your timetable as ics

**Comment by MatthiasReumann** [comment]
Yes, but you can only download one week and not the whole year. At least that's what I know and I can do at my school.

**Comment by AugustH** [comment]
you shouldn't have to download this, just enter the url into your outlook or gmail calendar

**Comment by MatthiasReumann** [comment]
There is no url.

**Comment by AugustH** [comment]
https://www.untis.at/Downloads/int/Manuals/de/WebUntis.pdf - Seite 24

**Comment by MatthiasReumann** [comment]
That's the old webuntis version. Our school has a newer one and it does not exist in the current one.

**Comment by MatthiasReumann** [comment]
<img width="491" alt="bildschirmfoto 2018-09-18 um 13 56 06" src="https://user-images.githubusercontent.com/29633518/45685731-a41ae480-bb4a-11e8-955b-7a36523d30fa.png">

Here is a picture of my "Freigaben". That's the reason why i wrote this script.
